<?php
/**
 * Breadcrub bar's HTML
 * 
 * @package Page
 * @subpackage Breadcrumbs
 * @category Html
 * @uses Page_Block_Html_Breadcrumbs
 * @copyright Copyright (c) 2010 Hettema&Bergsten
 * @author      
 */
?>
<div class="breadcumb-bar">
<?php if($crumbs && is_array($crumbs)): ?>
    <ul class="breadcrumbs">
    <?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
        <li class="<?php echo $_crumbName ?>">
        <?php if($_crumbInfo['link']): ?>
            <a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->htmlEscape($_crumbInfo['title']) ?>"><?php echo $this->htmlEscape($_crumbInfo['label']) ?></a>
        <?php elseif($_crumbInfo['last']): ?>
            <strong><?php echo $this->htmlEscape($_crumbInfo['label']) ?></strong>
        <?php else: ?>
            <?php echo $this->htmlEscape($_crumbInfo['label']) ?>
        <?php endif; ?>
        </li>
        <?php if(!$_crumbInfo['last']): ?>
        <li> / </li>
        <?php endif; ?>
    <?php endforeach; ?>
    </ul>
<?php endif; ?>
</div>