<?php
/**
 * Footer Pagelinks
 * 
 * @package Page
 * @subpackage Footer
 * @category Html
 * @uses Core_Block_Template
 * @copyright Copyright (c) 2010 Hettema&Bergsten
 * @author      
 */
?>
<footer id="footer">
	<?php if($this->getLayout()->getBlock('root')->getBodyClass() == 'home'): ?>
    <nav>
        <ul>
        	<li id="top"><a href="#" class="active"><strong>Top</strong></a></li>
            <li id="one"><a href="#"><strong>Visual Milestones</strong> Size matters! Full progress information at a glance</a></li>
            <li id="two"><a href="#"><strong>Who's Responsible?</strong> Put faces to Milestones</a></li>
            <li id="three"><a href="#"><strong>Suits &amp; Shirts</strong> Marketing &amp; development milestones are connected</a></li>
            <li id="four"><a href="#"><strong>The Full Picture</strong> Check out an example timeline</a></li>
            <li id="five"><a href="#"><strong>Open Source</strong> GNU, free, awesome! Join us!</a></li>
        </ul>
	</nav>
    
    <script type="text/javascript">
    /*$(document).ready(function() {    
        $('#features .scrollable').scrollable({ 
                size:1,
                autoplay:true,
                loop:true,
                speed:1000,
                vertical:true,
                clickable:true,
                keyboard:true
            }).navigator("#footer ul").circular().autoscroll({interval:10000});
    });*/
    </script>
    <?php endif ?>
</footer>
<div class="usr">
    <?php if($this->getSession()->getUser()): ?>
        <?php echo $this->getSession()->getUser()->getName() ?> | 
        <a href="javascript:stages.loadProjects(1)">Refresh Projects</a> |
        <a href="<?php echo $this->getUrl('project/create') ?>">Create Project</a> | 
        <a href="<?php echo $this->getUrl('project/index/view') ?>">View Project</a> | 
        <a href="<?php echo $this->getUrl('stages/index/logout') ?>">Sign out</a>
    <?php else: ?> 
        <a href="<?php echo $this->getUrl('stages/index/login') ?>">Sign in</a>
    <?php endif; ?>
</div>

<img src="<?php echo $this->getSkinUrl('img/border.png') ?>" id="border" />