<?php
/**
 * User Project listing page
 * @todo create a new block object
 * 
 * @package Stages
 * @subpackage User
 * @category Html
 * @uses Core_Block_Template
 * @copyright Copyright (c) 2010 Hettema&Bergsten
 * @author      
 */
?>
<div style="width: 100%; clear: both; display: block; position: static; margin-top: 100px;"></div>
List projects
<p class="btn btn_create"><a href="<?php echo $this->getUrl('project/create') ?>">Create new Project</a></p>