<?php
/**
 * List admin users
 * 
 * @package Admin
 * @subpackage User
 * @category Html
 * @uses Admin_Block_User_List
 * @copyright Copyright (c) 2010 Hettema&Bergsten
 * @author      
 */
?>
<?php echo $this->getChildHtml('toolbar') ?>
<?php
$collection = $this->getResultCollection()->getCollection();
$collection = empty ($collection) ? array() : $collection;
?>

<table cellpadding="0" cellspacing="0" border="0">
    <tr>
        <th>Name</th>
        <th>User name</th>
        <th>Email</th>
    </tr>
<?php foreach($collection as $_item): ?>
    <tr>
        <td><a href="<?php echo $this->getUrl('admin/user/edit') ?>?id=<?php echo $_item->getId(); ?>"><?php echo $_item->getFirstname() .' '.  $_item->getLastname()  ?></a></td>
        <td><?php echo $_item->getUsername()  ?></td>
        <td><?php echo $_item->getEmail(); ?></td>
    </tr><!-- end of row -->
<?php endforeach; ?>
</table>
<?php echo $this->getChildHtml('toolbar') ?>
