<?php
/**
 * Html Outline for 2 columm with right bar page view
 * 
 * @package Backend
 * @subpackage Page
 * @category Html
 * @uses Page_Block_Html
 * @copyright Copyright (c) 2010 Hettema&Bergsten
 * @author      
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body <?php echo $this->getBodyClass()?'class="'.$this->getBodyClass().'"':'' ?>>
<div class="container">
    <?php echo $this->getChildHtml('header') ?>
    <?php echo $this->getChildHtml('header_bottom') ?>
    <!-- [end] header -->
    <div class="outline-creator">
        <div class="middle layout-2columns-right">
            <div class="col-right sidebar" id="col-right">
            <?php echo $this->getChildHtml('right') ?>&nbsp;
            <!-- [end] col-right -->
            </div>
            <div class="col-main" id="main">
                <?php echo $this->getChildHtml('content') ?>
                <!-- [end] content -->
            </div>
        </div>
     </div>
     <div class="footer" id="footer">
     <?php echo $this->getChildHtml('footer') ?>
     </div>
</div>
<?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>