<?php
/**
 * Access denied page view HTML
 * 
 * @package Backend
 * @subpackage Page
 * @category Html
 * @uses Backend_Block_Template
 * @copyright Copyright (c) 2010 Hettema&Bergsten
 * @author      
 */
?>
<div style="height: 100px;">
    <div style="padding: 10px">
        <h1 style="color:red">No Access</h1>
        <div style="width:100%;">
            <p style="font-size: 14px; line-height: 20px;">We're sorry! You are not authorized to access this page.</p>
        </div> <!-- end of description -->
    </div>
</div>
