<?php
/**
 * 404 page not found
 * 
 * @package Backend
 * @subpackage Page
 * @category Html
 * @uses backend/template
 * @copyright Copyright (c) 2010 Hettema&Bergsten
 * @author      
 */
?>
<div style="height: 100px;">
    <div style="padding: 10px">
        <h1>Page not found</h1>
        <div style="width:100%;">
            <p style="font-size: 14px; line-height: 20px;">We're sorry! This page is not available.
                <a href="<?php echo $this->getUrl() ?>"> click here to go to homepage </a><!-- or use the search box below.--></p>
        </div> <!-- end of description -->
    </div>
</div>
