<?php
/**
 * Html Outline for  single columm page view
 * 
 * @package Page
 * @category Html
 * @copyright Copyright (c) 2010 Hettema&Bergsten
 * @author      
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>" xmlns:fb="http://www.facebook.com/2008/fbml" class="no-js home">
<?php echo $this->getChildHtml('head') ?>
<body class="<?php echo $this->getBodyClass() ?>">
    <?php if($this->getBodyClass() == 'home'):
        echo $this->getChildHtml('header_home');
    else: 
        echo $this->getChildHtml('header');
    endif; ?>
    <!-- [end] header -->
    
    <?php echo $this->getChildHtml('header_bottom') ?>
    <?php echo $this->getChildHtml('content') ?>
    <?php echo $this->getChildHtml('footer') ?>
    <!-- [end] content -->
<?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>