<?php
/**
 * 404 page not found
 * 
 * @package Page
 * @category Html
 * @uses Page_Block_Html
 * @copyright Copyright (c) 2010 Hettema&Bergsten
 * @author      
 */
?>
<div style="margin-top: 130px; margin-left: 200px; height: 400px;">
    <h1>Page not found</h1>
    <p style="font-size: 14px; line-height: 20px;">We're sorry! This page is not available.
                <a href="<?php echo App_Main::getUrl() ?>"> click here to go to homepage </a><!-- or use the search box below.--></p>
</div>
